from .action_comb_disc import FootsiesActionCombinationsDiscretized
from .normalization import FootsiesNormalized
from .statistics import FootsiesStatistics
from .frame_skip import FootsiesFrameSkipped